/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GymManagementSystem;

import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author My
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setSize(1850,1100);
        setLocation(50,0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        test = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_UserName = new javax.swing.JComboBox<>();
        jButton_Reset = new javax.swing.JButton();
        jButton_Exit = new javax.swing.JButton();
        jButton_Login = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        test.setText("jButton1");
        getContentPane().add(test);
        test.setBounds(1310, 170, 79, 25);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TO LOG IN");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(820, 100, 240, 100);

        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(840, 620, 41, 16);

        jComboBox_UserName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jComboBox_UserName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Ayan Chy", "Liza Jannat", "Mehjabin Warisa" }));
        jComboBox_UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_UserNameActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_UserName);
        jComboBox_UserName.setBounds(860, 240, 320, 40);

        jButton_Reset.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_Reset.setText("Reset");
        jButton_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ResetActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Reset);
        jButton_Reset.setBounds(930, 500, 160, 50);

        jButton_Exit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_Exit.setText("Exit");
        jButton_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Exit);
        jButton_Exit.setBounds(1180, 500, 160, 50);

        jButton_Login.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_Login.setText("Login");
        jButton_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Login);
        jButton_Login.setBounds(670, 500, 170, 50);

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(860, 320, 320, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PASSWORD");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(690, 330, 140, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("USERNAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(690, 250, 140, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 102));
        jLabel2.setText("LAM GYM CENTRE ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(730, 30, 610, 110);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GymManagementSystem/18848783802_698df9a75f_b.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(460, 40, 1670, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExitActionPerformed
        // TODO add your handling code here:
         int response = JOptionPane.showConfirmDialog(this, "Do you Want to Exit ?","Confirm",JOptionPane.YES_NO_OPTION ,JOptionPane.QUESTION_MESSAGE);
        if(response==JOptionPane.YES_OPTION){
        System.exit(0);
        }
    }//GEN-LAST:event_jButton_ExitActionPerformed

    private void jButton_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ResetActionPerformed
        // TODO add your handling code here:
         int response = JOptionPane.showConfirmDialog(this, "Do you Want to Reset ?","Confirm",JOptionPane.YES_NO_OPTION ,JOptionPane.QUESTION_MESSAGE);
        if(response==JOptionPane.YES_OPTION){
        jComboBox_UserName.setSelectedItem("None");
        jPasswordField1.setText(null); 
        }
        
    }//GEN-LAST:event_jButton_ResetActionPerformed

    private void jButton_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LoginActionPerformed
        // TODO add your handling code here:
        
        String password=jPasswordField1.getText();
        String username=(String) jComboBox_UserName.getSelectedItem();
        if(((password.contains("12345")) &&  (username.contains("Ayan Chy"))) || ((password.contains("23456")) &&  (username.contains("Liza Jannat"))) ||
                ((password.contains("34567")) &&  (username.contains("Mehjabin Warisa"))))
        {
          jComboBox_UserName.setSelectedItem("None");
          jPasswordField1.setText(null); 
          systemExit();
          JOptionPane.showMessageDialog(this, "Login Succesfully");
          MainSiteOfGymManagementSystem info=new MainSiteOfGymManagementSystem();
          info.setVisible(true);
          dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Wrong Password","Login Error",JOptionPane.ERROR_MESSAGE);
             jComboBox_UserName.setSelectedItem("None");
            jPasswordField1.setText(null);        
        }
        
    }//GEN-LAST:event_jButton_LoginActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jComboBox_UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_UserNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public  void login (){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Exit;
    private javax.swing.JButton jButton_Login;
    private javax.swing.JButton jButton_Reset;
    private javax.swing.JComboBox<String> jComboBox_UserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton test;
    // End of variables declaration//GEN-END:variables

 private void  systemExit()
    {
        WindowEvent winCloseing=new WindowEvent(this , WindowEvent.WINDOW_CLOSING);

    }

}
