/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GymManagementSystem;

import java.awt.List;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.ObjectOutputStream;
import static java.lang.ProcessBuilder.Redirect.to;
import static java.lang.System.out;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author My
 */
public class MainSiteOfGymManagementSystem extends javax.swing.JFrame {

    /**
     * Creates new form MainSiteOfBook
     */
    
    
    
    public MainSiteOfGymManagementSystem() {
        initComponents();
          setSize(1850,1000);
        setLocation(50,0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_StoreData = new javax.swing.JButton();
        jTextField_Address = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBox_Sex = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jTextField_Search_Code = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField_Fees = new javax.swing.JTextField();
        jTextField_Mobile = new javax.swing.JTextField();
        jTextField_Age = new javax.swing.JTextField();
        jTextField_MemberName = new javax.swing.JTextField();
        jTextField_Id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton_InsertAndSave = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton_Update = new javax.swing.JButton();
        jButton_Delete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton_StoreData.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_StoreData.setText("Insert Stored Data To Table");
        jButton_StoreData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_StoreDataActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_StoreData);
        jButton_StoreData.setBounds(1100, 520, 290, 50);

        jTextField_Address.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jTextField_Address);
        jTextField_Address.setBounds(580, 480, 200, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Address");
        jLabel10.setToolTipText("");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(470, 490, 71, 22);

        jComboBox_Sex.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBox_Sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Male", "Female", "Others" }));
        getContentPane().add(jComboBox_Sex);
        jComboBox_Sex.setBounds(580, 330, 200, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Sex");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(500, 340, 33, 22);

        jTextField_Search_Code.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_Search_Code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Search_CodeActionPerformed(evt);
            }
        });
        jTextField_Search_Code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Search_CodeKeyReleased(evt);
            }
        });
        getContentPane().add(jTextField_Search_Code);
        jTextField_Search_Code.setBounds(860, 520, 220, 50);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Search ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(790, 530, 70, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Member Id", "Member Name", "Age ", "Sex", "Mobile", "Monthly Fee", "Address", "Date", "Time"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(390, 620, 1000, 150);

        jTextField_Fees.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_Fees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_FeesActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Fees);
        jTextField_Fees.setBounds(580, 430, 200, 40);

        jTextField_Mobile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jTextField_Mobile);
        jTextField_Mobile.setBounds(580, 380, 200, 40);

        jTextField_Age.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jTextField_Age);
        jTextField_Age.setBounds(580, 280, 200, 40);

        jTextField_MemberName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_MemberName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_MemberNameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_MemberName);
        jTextField_MemberName.setBounds(580, 230, 200, 40);

        jTextField_Id.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IdActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Id);
        jTextField_Id.setBounds(580, 180, 200, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Monthly Fee");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(450, 440, 110, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mobile");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(480, 390, 140, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Age");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(500, 290, 120, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Member Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(440, 240, 132, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Member Id");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(450, 190, 130, 22);

        jButton_InsertAndSave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_InsertAndSave.setText("Insert/Save");
        jButton_InsertAndSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InsertAndSaveActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_InsertAndSave);
        jButton_InsertAndSave.setBounds(860, 180, 150, 50);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Logout");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(1110, 390, 120, 50);

        jButton_Update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Update.setText("Update");
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Update);
        jButton_Update.setBounds(950, 250, 120, 50);

        jButton_Delete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Delete.setText("Delete");
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Delete);
        jButton_Delete.setBounds(1030, 320, 110, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 102));
        jLabel1.setText("LAM GYM CENTRE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(660, 20, 470, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GymManagementSystem/18848783802_698df9a75f_b.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(380, -20, 1610, 820);

        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(1310, 70, 48, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this, "Do you Want to LogOut ?","Confirm",JOptionPane.YES_NO_OPTION ,JOptionPane.QUESTION_MESSAGE);
        if(response==JOptionPane.YES_OPTION){
        Login info=new Login();
          info.setVisible(true);
          dispose();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    
    String x,y;
    
    private void jTextField_FeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_FeesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_FeesActionPerformed
             
    public void readFile()
       {
        String filePath="C:/Users/COMPUTER WORLD/Desktop/New folder/GymManagementSystem/Data/store.txt";
           File file=new File(filePath);
           
        try
        {
            
            FileReader fr=new FileReader(file);
            BufferedReader br=new BufferedReader (fr);
            
            DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
            
            Object[] lines=br.lines().toArray();
            
            for(int i=0;i<lines.length;i++)
            {
                String[] row=lines[i].toString().split(" ");
                model.addRow(row);
            }  
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
      
       }
     
        public   void writeFile()
       {
          
           String filePath="C:/Users/COMPUTER WORLD/Desktop/New folder/GymManagementSystem/Data/store.txt";
           File file=new File(filePath);
           try
           {
               FileWriter fw=new FileWriter(file);
               BufferedWriter bw=new BufferedWriter(fw);
               
               for(int i=0;i<jTable1.getRowCount();i++){
                   for(int j=0;j<jTable1.getColumnCount();j++)
                   {
                       bw.write(jTable1.getValueAt(i, j).toString()+" ");
                   }
                   bw.newLine();
               }
            bw.close();
           fw.close();
           }
         
        catch(Exception e)
        {
            System.out.println("eeeaaa"+e);
        }
 
       }
        
    
   
    private void jButton_InsertAndSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InsertAndSaveActionPerformed
          // TODO add your handling code here:
     
        Clock cl=new Clock();
        cl.clock();
         x=cl.a;
         y=cl.b;
          
        int response = JOptionPane.showConfirmDialog(this, "Do you Want to Insert These Datas ?","Confirm",JOptionPane.YES_NO_OPTION ,JOptionPane.QUESTION_MESSAGE);
        if(response==JOptionPane.YES_OPTION){
     
        
        
    
        
       DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
       
     

       model.addRow(new Object[] {jTextField_Id.getText(),jTextField_MemberName.getText(),jTextField_Age.getText()
               ,jComboBox_Sex.getSelectedItem()
       ,jTextField_Mobile.getText(),jTextField_Fees.getText(),jTextField_Address.getText(),x,y});
         writeFile();
       
              //writeFile2(bookCode,bookName,writerName,publishedDate,price);
       jTextField_Id.setText(null);jTextField_MemberName.setText(null);jTextField_Age.setText(null)
               ;jComboBox_Sex.setSelectedItem("None");
       ;jTextField_Mobile.setText(null);jTextField_Fees.setText(null);jTextField_Mobile.setText(null);
       jTextField_Fees.setText(null);jTextField_Address.setText(null);
    
       
        
        }
    }//GEN-LAST:event_jButton_InsertAndSaveActionPerformed

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed
        // TODO add your handling code here:
        
          int response = JOptionPane.showConfirmDialog(this, "Do you Want to Delete Your Selected Datas ?","Confirm",JOptionPane.YES_NO_OPTION ,JOptionPane.QUESTION_MESSAGE);
        if(response==JOptionPane.YES_OPTION){
          DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
          if(jTable1.getSelectedRow()==-1){
              if(jTable1.getRowCount()==0){
                  JOptionPane.showMessageDialog(null, "No Data Deleted","GYM Management System",JOptionPane.OK_OPTION);
              }
              else{
                  JOptionPane.showMessageDialog(null, "Selected  Row Data Was Deleted","GYM Management System",JOptionPane.OK_OPTION);
                   
                  
              }
              
          }
          else
              {
                      model.removeRow(jTable1.getSelectedRow());
                      
                       jTextField_Id.setText(null);jTextField_MemberName.setText(null);jTextField_Age.setText(null)
               ;jComboBox_Sex.setSelectedItem("None");
       ;jTextField_Mobile.setText(null);jTextField_Fees.setText(null);jTextField_Mobile.setText(null);
       jTextField_Fees.setText(null);jTextField_Address.setText(null);
                      }
        }
        writeFile();
    }//GEN-LAST:event_jButton_DeleteActionPerformed

    private void jTextField_Search_CodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Search_CodeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField_Search_CodeActionPerformed

    private void jTextField_Search_CodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Search_CodeKeyReleased
        // TODO add your handling code here:
        
        DefaultTableModel modell= (DefaultTableModel) jTable1.getModel();
        String search=jTextField_Search_Code.getText();
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(modell);
        jTable1.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
        
    }//GEN-LAST:event_jTextField_Search_CodeKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int selectedRow = jTable1.getSelectedRow();
        
        DefaultTableModel model3= (DefaultTableModel) jTable1.getModel();
        
        jTextField_Id.setText(model3.getValueAt(selectedRow,0).toString());
        jTextField_MemberName.setText(model3.getValueAt(selectedRow,1).toString());
        jTextField_Age.setText(model3.getValueAt(selectedRow,2).toString());
        //jComboBox_Sex.getSelectedItem.(model3.getValueAt(selectedRow,3));
        
        jComboBox_Sex.setSelectedItem(model3.getValueAt(selectedRow,3).toString());
        jTextField_Mobile.setText(model3.getValueAt(selectedRow,4).toString());
        jTextField_Fees.setText(model3.getValueAt(selectedRow,5).toString());
        jTextField_Address.setText(model3.getValueAt(selectedRow,6).toString());
        x=(model3.getValueAt(selectedRow, 7).toString());
        y=(model3.getValueAt(selectedRow,8).toString());
            

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked
      int c=1;
    private void jButton_StoreDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_StoreDataActionPerformed

        
     int response = JOptionPane.showConfirmDialog(this, "Do you Want to Insert Privious Datas  ?","Confirm",JOptionPane.YES_NO_OPTION ,JOptionPane.QUESTION_MESSAGE);
        if(response==JOptionPane.YES_OPTION){
        if(c==1){
        readFile();
        c--;
    }
        else
        {
            JOptionPane.showMessageDialog(null,"Datas are aleady Existed","Already Existed",JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_jButton_StoreDataActionPerformed

    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed
        // TODO add your handling code here:
         int response = JOptionPane.showConfirmDialog(this, "Do you Want to Update Your Selected Datas ?","Confirm",JOptionPane.YES_NO_OPTION ,JOptionPane.QUESTION_MESSAGE);
        if(response==JOptionPane.YES_OPTION){
             DefaultTableModel modell= (DefaultTableModel) jTable1.getModel();
            int i=jTable1.getSelectedRow();
            if(i>=0)
            {
         modell.setValueAt(jTextField_Id.getText(), i, 0);
         modell.setValueAt(jTextField_MemberName.getText(), i, 1);
         modell.setValueAt(jTextField_Age.getText(), i, 2);
        ///jComboBox_Sex.getSelectedItem.(model3.getValueAt(selectedRow,3));
        modell.setValueAt(jComboBox_Sex.getSelectedItem(), i, 3);
        modell.setValueAt(jTextField_Mobile.getText(), i, 4);
        modell.setValueAt(jTextField_Fees.getText(), i, 5);
        modell.setValueAt(jTextField_Address.getText(), i, 6);
        modell.setValueAt(x, i, 7);
        modell.setValueAt(y, i, 8);
        
           jTextField_Id.setText(null);
           jTextField_MemberName.setText(null);
           jTextField_Age.setText(null);
           jComboBox_Sex.setSelectedItem("None");
           jTextField_Mobile.setText(null);
           jTextField_Fees.setText(null);
           jTextField_Mobile.setText(null);
       jTextField_Fees.setText(null);
       jTextField_Address.setText(null);
        
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Error");
            }
            
        }
        writeFile();
    }//GEN-LAST:event_jButton_UpdateActionPerformed

    private void jTextField_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IdActionPerformed

    private void jTextField_MemberNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_MemberNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_MemberNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
       
          
         
       
        
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainSiteOfGymManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainSiteOfGymManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainSiteOfGymManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainSiteOfGymManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 
                new MainSiteOfGymManagementSystem().setVisible(true);
            }
        });
    }
    
   
    
    
  
    
   
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_InsertAndSave;
    private javax.swing.JButton jButton_StoreData;
    private javax.swing.JButton jButton_Update;
    private javax.swing.JComboBox<String> jComboBox_Sex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_Address;
    private javax.swing.JTextField jTextField_Age;
    private javax.swing.JTextField jTextField_Fees;
    private javax.swing.JTextField jTextField_Id;
    private javax.swing.JTextField jTextField_MemberName;
    private javax.swing.JTextField jTextField_Mobile;
    private javax.swing.JTextField jTextField_Search_Code;
    // End of variables declaration//GEN-END:variables
}
